### ISSUE TITLE
Automation LDAP Sync

### ISSUE THREAD

**Issue by Elkanta** [DiouxX/docker-glpi#110]
Hello,

I've a problem for automation of user import and synchronization, when I use command I've this error :

```
sudo php bin/console ldap:synchronize_users
The GLPI codebase has been updated. The update of the GLPI database is necessary.
Run the "php bin/console database:update" command to process to the update.
```

So when I try to update database I've this error : 

```
php bin/console database:update
Unable to connect to database.
database:update [-u|--allow-unstable] [-s|--skip-db-checks] [-f|--force] [--enable-telemetry] [--no-telemetry]
```

I've check requirements with command "php bin/console system:check_requirements" and I've all required
I've configure my LDAP on graphic interface, connection is ok. I can import & synch manually users

So I don't know I've this error, maybe it's because it's a docker configuration ? 
My GLPI is on version 10.0.13

Regards

**Comment by DiouxX** [comment]
Hello,

Have you tried running the database upgrade with the following command  :

`
docker exec glpi php /var/www/html/glpi/bin/console database:update
`

What is your docker-compose file ?

**Comment by Elkanta** [comment]
Hello

I've test your command but don't work, I don't have folder /var/www/html/glpi

My docker-compose file is 


```
version: '3.2'

services:
# mariaDB Container
  db:
    image: mariadb:10.11-rc
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - ./db:/var/lib/mysql
    ports:
      - 3306:3306

    env_file:
     - ./mariadb.env

#GLPI Container
  app:
    image: diouxx/glpi
    container_name : glpi
    restart: always
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./data:/var/www/html/glpi
```

Regards,
