### ISSUE TITLE
Can I change mariadb host target ?

### ISSUE THREAD

**Issue by edgardeloire** [DiouxX/docker-glpi#126]
Hello,
I need to relocate mariadb db  on on shared mariadb server (bd-host ?) is there a way to tell glpi container to address a different host ? :

```
# shared db server for backend
services:
  mariadb-server:
    image: mariadb:latest
    container_name: mariadb-server
    hostname:  mariadb-server
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpi_password
    volumes:
      - /data/mariadb_data:/var/lib/mysql
    networks:
      - proxy-net
networks:
  proxy-net:
    name: proxy-net
    external: true
```

 ```                                                                                                  
services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    environment:
      - TIMEZONE=Europe/Paris
      - DB_HOST=mariadb-server # <---- ?? Not working 
      - GLPI_DB_HOST=mariadb-server  #<??---- Not working 
    volumes:
      - /users/glpi/glpi_data:/var/www/html/glpi
#    depends_on:
#      - mariadb
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glpi.rule=Host(******************`)"
      - "traefik.http.routers.glpi.entrypoints=websecure"
      - "traefik.http.routers.glpi.tls=true"
      - "traefik.http.routers.glpi.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.glpi.tls.domains[0].main=************************"


networks:
  proxy-net:
    name: proxy-net
    external: true

```
Error 

GLPI SETUP
Étape 2
Test de connexion à la base de données
Impossible de se connecter à la base de données
**Le serveur a répondu : php_network_getaddresses: getaddrinfo for mariadb failed: Temporary failure in name resolution**
