### ISSUE TITLE
Busybox container its necesary?

### ISSUE THREAD

**Issue by Nitrosito** [DiouxX/docker-glpi#20]
Hi
Why exist in docker-compose:
```

  glpi-data:
    image: busybox
    container_name: glpi-data
    volumes:
- /var/www/html/glpi:/var/www/html/glpi

```
insted of... remove glpi-data and mount directly /var/www/html/glpi:/var/www/html/glpi in GLPI Custom image.

¿Why use busybox? Thanks and regards
