### ISSUE TITLE
Feature Request: Add Support for SNMP

### ISSUE THREAD

**Issue by houstek** [DiouxX/docker-glpi#21]
Hi,
Would it be possible to include SNMP extension in your image? This is necessary for some plugins: 
https://github.com/InfotelGLPI/printercounters/wiki/Notice-d%E2%80%99utilisation

Thx

**Comment by DiouxX** [comment]
Hi,

I've added SNMP package and i have configured for him listen on port 161 : 58ff53e00b650a35c9f4ebd54c338edf0988349c

To check if it's all right for you, please test with _diouxx/glpi:dev_

Here, adapated docker-compose file

```yaml
version: "3"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env

#GLPI Container
  glpi:
    image: diouxx/glpi:dev
    container_name : glpi-dev
    hostname: glpi-dev
    ports:
      - "80:80"
    links:
      - mysql:mysql
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
restart: always
```

If its all right, i will merge with master branch later
