### ISSUE TITLE
What is the glpi password?

### ISSUE THREAD

**Issue by andreenumo** [DiouxX/docker-glpi#22]
Deploy GLPI without database

What is the login, password, default hostname to connect to in glpi?
I installed glpi but I can not login and password

**Comment by andreenumo** [comment]
Database connection parameters
SQL server (MariaDB or MySQL) 

SQL user 

SQL password 

default password?

**Comment by DiouxX** [comment]
It's not possible to run Glpi without database.
The documentation need updated, sorry...

If you want run Glpi, you can use [docker-compose](https://github.com/DiouxX/docker-glpi/blob/master/docker-compose.yml) it's easiest and you set hitself MYSQL password and MYSQL database with [mysql.env](https://github.com/DiouxX/docker-glpi/blob/master/mysql.env) file

If you want run Glpi without persitance data for quickly test, you can use docker-compose  by removing volumes lines : 
```yaml
version: "3"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    links:
      - mysql:mysql
```
