### ISSUE TITLE
Change timezone

### ISSUE THREAD

**Issue by DiouxX** [DiouxX/docker-glpi#4]
Ability to change timezone for time used by fusioninevntory plugin

**Comment by DiouxX** [comment]
It is also possible to override the docker container timezone by appending the following volumes:
`-v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime`

and on docker file :
```yml
#GLPI Container
glpi:
 image: diouxx/glpi
 container_name : glpi
 hostname: glpi
 external_links:
  - mysql:mysql
 volumes:
 - /etc/timezone:/etc/timezone
 - /etc/localtime:/etc/localtime
 volumes_from:
  - web-data
 restart: always
```
