### ISSUE TITLE
V10 for test

### ISSUE THREAD

**Issue by Sailman83** [DiouxX/docker-glpi#46]
Hello,

Will work to update to v10 ?

Because, I would like make some tests with beta version before update to production

Thanks

**Comment by DiouxX** [comment]
Hello,

Sorry but you are talking about version 10 of which component?
Debian or another one?

**Comment by Sailman83** [comment]
Hello,

Anyone Linux distribution.

Juste an installation V10 on Docker to do some test.

Thanks
________________________________

**Comment by DiouxX** [comment]
Sorry but I still don't understand which version you are talking about
I suppose it is compatible in many situations.

I can only advise you to do the test and we will see the result.

**Comment by Sailman83** [comment]
I talk about New version 10 in bête status.

We can download in standard package. I would like test in docker container.
________________________________

**Comment by DiouxX** [comment]
Can't you specify that you are talking about the version of Glpi?

If you want to test, it is enough to specify the version during the deployment.
It is specified in the Readme

Personally, I haven't tested it yet

**Comment by Sailman83** [comment]
I use Docker-compose.
I don’t know how specify the versi with this 😥

**Comment by DiouxX** [comment]
You can use the [environnement](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers) key in your docker-compose file

Your docker-compose file might look like this :

```yaml
version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    environment:
      - VERSION_GLPI=10.0.0-beta
    ports:
      - "80:80"
```

i have tested and it's the 10.0.0-beta which is deployed
