### ISSUE TITLE
ARM image

### ISSUE THREAD

**Issue by fam4r** [DiouxX/docker-glpi#62]
Hello, can you please provide an ARMv8 version for the image?
Thanks

**Comment by zimbres** [comment]
Try: https://github.com/zimbres/glpi-docker

**Comment by ozturkinc** [comment]
I had this very same problem when I was trying to get it up and running on my Macbook Pro M1.
It seems Maria DB already supports arm. It is the the glpi container that is the problem.
I have managed to get around this using below small addition to docker-compose.yml file (not sure what is the equivalent for docker run):

```
version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    platform: linux/x86_64
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
    restart: always
```

You need to add **"platform: linux/x86_64"**. Once this is done, my containers went up without a problem and I managed to run GLPI.
