### ISSUE TITLE
Cannot connect to database server

### ISSUE THREAD

**Issue by jlgarnier** [DiouxX/docker-glpi#63]
Hi all,

Just gave a try to the tool using "Deploy with persistence data" scenario. Installation went smooth and I got immediate access to the installation wizard. When asked to connect to the database, I enter:
- SQL server = mariadb (hostname)
- SQL user = glpi_user
- SQL password = glpi
as given by the .env file. Then get a "php_network_getaddresses: getaddrinfo failed: Name or service not known " error... Both app and database containers look up and running fine.

Did anyone else stumble of this issue at first launch?

Thanks in advance for any help!

Edit: I alternatively get "No route to host" message...

**Comment by jlgarnier** [comment]
The YAML file is exactly the same:
```
version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: glpi-db
    hostname: mariadb
    volumes:
      - /srv/dev-disk-by-label-omvdata/docker/glpi/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi-app
    hostname: glpi
    ports:
      - "14000:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-label-omvdata/docker/glpi/html:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Paris
    restart: always
```

as is the config file:
```
MARIADB_ROOT_PASSWORD=R00tP4ssw0rd
MARIADB_DATABASE=glpidb
MARIADB_USER=glpi_user
MARIADB_PASSWORD=glpi
```

I'm using the above parameters to fill the connection form:
![Capture d’écran 2022-06-21 131024](https://user-images.githubusercontent.com/26840059/174785975-ba15092a-3d34-4891-b27b-a90f339954de.png)

Where am I wrong?

Thanks in advance for your help!
