### ISSUE TITLE
issue with time zone

### ISSUE THREAD

**Issue by killmasta93** [DiouxX/docker-glpi#72]
Hi i was wondering if someone else has had this issue, currently installing GLPI using docker compose but when i check on timezone it shows on the general settings

`The use of the time zone has not been activated. Run the command "php bin/console glpi:database:enable_timezones" to activate it. `

```
version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /scsi2/glpi/db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /scsi2/glpi/mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "8096:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /scsi2/glpi/html:/var/www/html/glpi:rw
    environment:
      - TIMEZONE=America/Bogota
    restart: always
```
 ```
cat mariadb.env
MARIADB_ROOT_PASSWORD=mypass
MARIADB_DATABASE=glpidb
MARIADB_USER=glpi_user
MARIADB_PASSWORD=mypass
TZ=America/Bogota

```

Thank you
