### ISSUE TITLE
Quick docker-compose file gives a 404 error not found

### ISSUE THREAD

**Issue by Zoubeyer** [DiouxX/docker-glpi#74]
Hi,

I just wanted to test GLPI so I use the "qucik" docker-compose file (I'm on Windows 10) :

```
version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
```

With this file, Docker-compose seems to run well :
```
PS D:\Docker\GLPI9> docker-compose up -d
[+] Running 17/17
 - mariadb Pulled                                                           23.1s
   - fb0b3276a519 Pull complete                                              5.2s
   - 825c4435e9b4 Pull complete                                              5.3s
   - c48535fb256b Pull complete                                              7.0s
   - 65142e3bf01b Pull complete                                              8.5s
   - c994327ef3cc Pull complete                                              8.7s
   - 40d12c21872a Pull complete                                             10.8s
   - dd18621bd4ea Pull complete                                             11.0s
   - 96fce08721d8 Pull complete                                             12.9s
   - a3382bbf58b1 Pull complete                                             19.3s
   - 29ef56bd39f8 Pull complete                                             19.5s
   - 94282ba424a5 Pull complete                                             19.6s
 - glpi Pulled                                                              17.8s
   - 5e0b432e8ba9 Pull complete                                              9.1s
   - e5cf215f1f54 Pull complete                                             14.7s
   - 5de8d69fb37e Pull complete                                             14.8s
   - 87556a5b0159 Pull complete                                             15.0s
[+] Running 3/3
 - Network glpi9_default  Created                                            0.1s
 - Container mariadb      Started                                            2.6s
 - Container glpi         Started                                            2.5s
PS D:\Docker\GLPI9>
```

But when I try to access GLPI (http://localhost:80) I have a "404 error - not found" : 

```
Not Found

The requested URL was not found on this server.
Apache/2.4.53 (Debian) Server at localhost Port 80
```

Has anyone been able to use this docker-compose file (for quickly test) ?

**Comment by DiouxX** [comment]
Hello,

I can't test on Windows.
I just tried with Docker Desktop and WSL with the same docker-compose file

```yaml
version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
```

and i haven't the error

```
diouxx@host:/tmp$ docker-compose -f docker-compose-glpi.yml up -d
[+] Running 3/3
 ⠿ Network tmp_default  Created                                                                                    0.0s
 ⠿ Container glpi       Started                                                                                    1.4s
 ⠿ Container mariadb    Started                                                                                    1.4s
diouxx@host:/tmp$ docker-compose -f docker-compose-glpi.yml ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
glpi                "/opt/glpi-start.sh"     glpi                running             0.0.0.0:80->80/tcp, 443/tcp
mariadb             "docker-entrypoint.s…"   mariadb             running             3306/tcp
```

When I go on http://localhost, I have the GLPI installation web page
