### ISSUE TITLE
VERSION_GLPI=10.0.5 not working

### ISSUE THREAD

**Issue by rafaelllourenco** [DiouxX/docker-glpi#78]
Hello,

I have deployed GLPI using docker-compose and the environment variable for the version is not working.

Please find my docker-compose.yml below:

```
#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Luxembourg
      - VERSION_GLPI=10.0.5
    restart: always
    networks:
      glpi_network:
        ipv4_address: 172.30.0.3
```
And the version in the GUI...
![image](https://user-images.githubusercontent.com/63660923/201071695-3e5fefaa-8d5a-4186-af65-b88ade05959c.png)

Do you know what is the root cause or is this feature implemented?

Thank you!
