### ISSUE TITLE
GLPI Docker Port Configuration

### ISSUE THREAD

**Issue by TheTechnologyStudio** [DiouxX/docker-glpi#99]
Hello, How can i change the ports GLPI uses with docker-compose file? 

I need to set it to a non standard port.

Thanks

**Comment by DiouxX** [comment]
Hello,

You can find more information about port mapping into docker-compose documentation : https://docs.docker.com/compose/networking/

```yaml
#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "EXTERNAL-PORT:80"
```
